- hosts: test2
  vars:
     uusername: dkrasnov
     ps: PsdjLnr398wrvn
#    part: "/dev/xvdc"
#    path_src: "/home/mitrofanov/old/"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: create-user }
