---
# tasks file for nfs_from_mount

- name: Проверка установки nfs-server
  become: yes
  become_method: sudo
  become_user: root
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-server

- name: Добавление timeout в Zabbix
  lineinfile:
    path: '/etc/exports'
    line: '{{ item }}'
  with_items: "{{ path_to_shared }}"

- name: Остановка службы
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nfs-server

